#' Simulated Data from a Poisson Selection Model
#'
#' A data set drawn with [simulate_poisselect()] from the model of
#' [poisselect()] with known parameters, used in the examples and in the tests.
#' Roughly 60 percent of the units are selected.
#'
#' @format A `data.frame` with 800 rows and 6 columns:
#' \describe{
#'   \item{y}{integer count outcome, `NA` for the non-selected units.}
#'   \item{s}{integer selection indicator, 0 or 1.}
#'   \item{x1}{numeric covariate of both equations.}
#'   \item{x2}{numeric covariate of the outcome equation only.}
#'   \item{z1}{numeric exclusion restriction, entering the selection equation
#'     only.}
#'   \item{y_complete}{integer count outcome of every unit, including the
#'     non-selected ones. Never used by the model; it only serves to
#'     demonstrate the size of the selection bias.}
#' }
#'
#' @details
#' The true parameters are `beta = c(0.5, 0.8, -0.4)` for `(Intercept)`, `x1`
#' and `x2`, `gamma = c(0.3, 0.5, 0.7)` for `(Intercept)`, `x1` and `z1`,
#' `sigma = 0.6` and `rho = 0.5`.
#'
#' @source Generated by `data-raw/sim_selection.R` with `set.seed(20240501)`
#'   and `simulate_poisselect(n = 800, beta = c(0.5, 0.8, -0.4), gamma =
#'   c(0.3, 0.5, 0.7), sigma = 0.6, rho = 0.5)`.
#'
#' @examples
#' str(sim_selection)
#' table(sim_selection$s)
#'
#' # The selection bias is visible without fitting anything: among the selected
#' # units the average outcome is higher than in the full population.
#' mean(sim_selection$y, na.rm = TRUE)
#' mean(sim_selection$y_complete)
"sim_selection"
